service: bandlab-backend

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  createPost:
    handler: handler.createPost
    events:
      - http:
          path: posts
          method: post

  addComment:
    handler: handler.addComment
    events:
      - http:
          path: posts/{postId}/comments
          method: post

resources:
  Resources:
    PostEventsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: PostEventsTopic

    PostEventsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PostEventsQueue

    PostEventsQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: PostEventsQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: AllowSNSToSendMessage
              Effect: Allow
              Principal: "*"
              Action: sqs:SendMessage
              Resource:
                Fn::GetAtt:
                  - PostEventsQueue
                  - Arn
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: PostEventsTopic
plugins:
  - serverless-offline